export const carsData = [
  {
    id: 1,
    title: 'BMW E21',
    category: 'E21',
    year: 1975,
    img: './images/item-1.jpeg',
    desc: `Prva generacija, model E21, se proizvodio od 1975. do 1983. godine. Proizvodio se u samo dvije karoserijske izvedbe - kao coupe i cabrio.`,
  },
  {
    id: 2,
    title: 'BMW E30',
    category: 'E30',
    year: 1982,
    img: './images/item-5.jpeg',
    desc: `Druga generacija, model E30, se proizvodio od 1982. do 1990. godine. Poznatiji kao "kockica", prvi puta je u trojku ugrađen i dizelski motor.`,
  },
  {
    id: 3,
    title: 'BMW E36',
    category: 'E36',
    year: 1991,
    img: './images/item-8.jpeg',
    desc: `Treća generacija, model E36, se proizvodio od 1991. do 2000. godine. Limuzina s četvero vrata je u Europi prodavana od jeseni 1991.`,
  },
  {
    id: 4,
    title: 'BMW E46',
    category: 'E46',
    year: 1998,
    img: './images/item-6.jpeg',
    desc: `Četvrta generacija, model E46, se proizvodio od 1998. do 2006. godine. Redizajniran je 2002. godine. 1998. se na tržištu pojavila limuzina.`,
  },
  {
    id: 5,
    title: 'BMW E90',
    category: 'E90',
    year: 2005,
    img: './images/item-9.jpeg',
    desc: `Peta generacija, model E90/91/92/93, se proizvodi od 2005. godine kao limuzina i karavan.`,
  },
  {
    id: 6,
    title: 'BMW F30',
    category: 'F30',
    year: 2012,
    img: './images/item-13.jpeg',
    desc: `Šesta generacija Serije 3 je predstavljena 14. listopada 2011. u Munich-u. U prodaji će biti početkom veljače 2012. godine. BMW je radio na novom modelu pune 4 godine.`,
  },
  {
    id: 7,
    title: 'BMW G20',
    category: 'G20',
    year: 2019,
    img: './images/item-14.jpeg',
    desc: `Sedma generacija asortimana BMW serije 3 sastoji se od BMW G20 i BMW G21. G20/G21 proizvodi se od sredine listopada 2018., u prodaji je od 2019.`,
  },
  {
    id: 8,
    title: 'BMW E46',
    category: 'E46',
    year: 1998,
    img: './images/item-7.jpeg',
    desc: `Četvrta generacija, model E46, se proizvodio od 1998. do 2006. godine. Redizajniran je 2002. godine. 1998. se na tržištu pojavila limuzina.`,
  },
  {
    id: 9,
    title: 'BMW E90',
    category: 'E90',
    year: 2005,
    img: './images/item-10.jpeg',
    desc: `Peta generacija, model E90/91/92/93, se proizvodi od 2005. godine kao limuzina i karavan. `,
  },
  {
    id: 10,
    title: 'BMW F30',
    category: 'F30',
    year: 2012,
    img: './images/item-11.jpeg',
    desc: `Šesta generacija Serije 3 je predstavljena 14. listopada 2011. u Munich-u. U prodaji će biti početkom veljače 2012. godine. BMW je radio na novom modelu pune 4 godine.`,
  },
  {
    id: 11,
    title: 'BMW E21',
    category: 'E21',
    year: 1975,
    img: './images/item-2.jpeg',
    desc: `Prva generacija, model E21, se proizvodio od 1975. do 1983. godine. Proizvodio se u samo dvije karoserijske izvedbe - kao coupe i cabrio.`,
  },
  {
    id: 12,
    title: 'BMW F30',
    category: 'F30',
    year: 2012,
    img: './images/item-12.jpeg',
    desc: `Šesta generacija Serije 3 je predstavljena 14. listopada 2011. u Munich-u. U prodaji će biti početkom veljače 2012. godine. BMW je radio na novom modelu pune 4 godine.`,
  },
  {
    id: 13,
    title: 'BMW E30',
    category: 'E30',
    year: 1982,
    img: './images/item-4.jpeg',
    desc: `Druga generacija, model E30, se proizvodio od 1982. do 1990. godine. Poznatiji kao "kockica", prvi puta je u trojku ugrađen i dizelski motor.`,
  },
  {
    id: 14,
    title: 'BMW E21',
    category: 'E21',
    year: 1975,
    img: './images/item-3.jpeg',
    desc: `Prva generacija, model E21, se proizvodio od 1975. do 1983. godine. Proizvodio se u samo dvije karoserijske izvedbe - kao coupe i cabrio.`,
  },
  {
    id: 15,
    title: 'BMW G20',
    category: 'G20',
    year: 2019,
    img: './images/item-15.jpeg',
    desc: `Sedma generacija asortimana BMW serije 3 sastoji se od BMW G20 i BMW G21. G20/G21 proizvodi se od sredine listopada 2018., u prodaji je od 2019.`,
  },
];
